### PR TITLE
handle the search

### PR DESCRIPTION
**Pull request by MohammedAlkutrani**
handle searching for file or directory in user's dropbox

### CODE REVIEW

**Comment by freekmurze** [comment]
Thank you, could you also update the readme with an example?

**Comment by MohammedAlkutrani** [comment]
Okay @freekmurze , I'll do it

**Comment by MohammedAlkutrani** [comment]
hey @freekmurze, you guys have a link to all the methods on `Client Class`.
and you only explained the usage of two:  `contentEndpointRequest` and `rpcEndpointRequest`, so if someone doesn't find his preferred method, he can create a new one using these two.

**Comment by freekmurze** [comment]
I'll pull it in like it is now, and document all the functions later.

Thanks!

**Comment by MohammedAlkutrani** [comment]
ok, thank you. @freekmurze take look at https://github.com/spatie/ssh/pull/7#issue-370686240

**Pull request merged**
