### PR TITLE
Ability to set custom headers added to use Team APIs

### PR DESCRIPTION
**Pull request by rathodbhavikkqc**
We were facing issues to set custom headers for using Team APIs, we have also checked in Issues for solution from where we have found an [open issue from Dec 2019](https://github.com/spatie/dropbox-api/issues/58).  So we have added this thing.

### CODE REVIEW

**Comment by freekmurze** [comment]
Could you update the readme and also add a test to prove that this works?

**Comment by rathodbhavikkqc** [comment]
Hey, how can i provide working example? I have used this in my implementation

**Comment by underthecocotree** [comment]
Hey,

I was trying to do the same with Flysystem which uses this repo.  I got frustrated that this code was not published yet.  I found another way to work around the headers without having to add any additional code.

You configure the guzzle client to add the header and pass the object for the Client.php to use.

Spatie\Dropbox\Client already accepts in the [constructor](https://github.com/spatie/dropbox-api/blob/9fe741364569beb851f3c26c08dc7f76ecdd39cd/src/Client.php#L54) a [GuzzleClient (GuzzleHttp\Client)](https://github.com/spatie/dropbox-api/blob/9fe741364569beb851f3c26c08dc7f76ecdd39cd/src/Client.php#L7) as  the second argument

```php
use Spatie\Dropbox\Client;
use GuzzleHttp\Client as GuzzleClient;

// [...]

$guzzle = new GuzzleClient([
    'headers' => [
        'Authorization' => "Bearer {$authorisation_token}",
        'Dropbox-API-Path-Root' => '{".tag": "namespace_id", "namespace_id": "$NAMESPACE_ID"}'
    ],
]);

$client = new Client($authorisation_token, $guzzle);
```

You can basically pass any headers you like when you initialise the class. It seemed to work for me.  Let me know if you need any more clarification.
Phoebus

**Comment by jacobmulquin** [comment]
I'm interested in this feature to be able to set the "Dropbox-API-Path-Root" header.

**Pull request closed without merging**
