### PR TITLE
Fix missing `.tag` from uploadSessionFinish response

### PR DESCRIPTION
**Pull request by iget-master**
This fixes the bug related by @chris-faulkner on PR #21

### CODE REVIEW

**Comment by chris-faulkner** [comment]
Nice work
Is there an easy way for me to pull a PR into my Laravel project to help test?

**Comment by iget-master** [comment]
@chris-faulkner You can require directly from my fork on composer to test. I never did this, but found this topic on stackoverflow that you can follow:

https://stackoverflow.com/questions/13498519/how-to-require-a-fork-with-composer

My fork is iget-master/dropbox-api please use the branch patch-1

**Comment by freekmurze** [comment]
Thank you very much

**Comment by chris-faulkner** [comment]
I tried pulling your branch in to test but couldn't get it to work with other Spatie package dependency requirements, so I just copied your changes directly and it worked without errors.
Thanks for your great work once again!

**Pull request merged**
